---
# Role download tasks

- block:
    - include_tasks: tempdir.yml
    - include_tasks: artifact.yml
  tags:
    - role::symantec_av
    - role::symantec_av::install
    - role::symantec_av::uninstall
