---
# Role tasks

- name: "check SymantecAV version"
  include_tasks: sav_version.yml
  tags:
    - role::symantec_av::version

- debug:
    msg: "required symantec_av_state: {{symantec_av_state}}"

- name: "Install SymantecAV"
  include_tasks: sav_install.yml
  when: >-
    symantec_av_state == "present"
    and symantec_av_needs_install == true

  # and symantec_av_version_installed != symantec_av_version

- name: "uninstall SymantecAV"
  include_tasks: sav_uninstall.yml
  tags:
    - role::symantec_av::uninstall
  when: >-
    symantec_av_state == "absent"
#    and symantec_av_version_installed != ''

- name: "service status"
  include_tasks: sav_services_check.yml
  tags:
    - role::symantec_av::check_services
