---
# Role service tasks

- debug: msg="{{ symantec_av_state == 'absent' }}"
  tags:
    - role::symantec_av
    - role::symantec_av::service

- name: Setup SymantecAV services
  service:
    name: "{{ symantec_av_service }}"
    state: >-
      {{ (symantec_av_state == "present")
         | ternary("started", "stopped") }}
    enabled: "{{ symantec_av_state == 'present' }}"
  ignore_errors: >-
    {{ (symantec_av_state == "absent") | ternary("yes", "no") }}
  loop:
    - symcfgd
    - rtvscand
    - smcd
  loop_control:
    loop_var: symantec_av_service
  tags:
    - role::symantec_av
    - role::symantec_av::service
