---
# Role service tasks

- name: Setup SymantecAV services # noqa ignore-errors
  service:
    name: "{{ symantec_av_service }}"
    state: >-
      {{ (symantec_av_state in ["force", "present"])
         | ternary("started", "stopped") }}
    enabled: "{{ symantec_av_state in ['force', 'present'] }}"
  ignore_errors: >-
    {{ (symantec_av_state == "absent") | ternary("yes", "no") }}
  loop:
    - symcfgd
    - rtvscand
    - smcd
  loop_control:
    loop_var: symantec_av_service
  tags:
    - role::symantec_av
    - role::symantec_av::service
